### PR TITLE
Updating to reflect possibly changed manifest file name.

### PR DESCRIPTION
**Pull request by Erutan409**

### CODE REVIEW

**Comment by ctf0** [comment]
does `mix.manifest.name` has a default ?

**Comment by Erutan409** [comment]
@ctf0 It does have a default, but you can change it if desired during the build process.

**Comment by ctf0** [comment]
i just wanted to make sure that when using `${Mix.manifest.name}` we wont get `undefined` on build

**Comment by Erutan409** [comment]
@ctf0 it's set , [here](https://github.com/JeffreyWay/laravel-mix/blob/d432101c23198252e3952d8d89ee246d209265a8/src/Manifest.js#L10).

**Comment by ctf0** [comment]
awesome, thanx for ur work

**Comment by ctf0** [comment]
@Erutan409 have u tested the logic, because i think `Mix` should be `mix`

**Comment by Erutan409** [comment]
@ctf0 Yeah, sorry - I just saw this last reply.  As noted [here], yup it should be Mix.

**Pull request merged**
