### PR TITLE
Update mix file removal

### PR DESCRIPTION
**Pull request by Erutan409**
* Did some format refactoring
* Added event listener that mimics the [MockEntryPlugin](https://github.com/JeffreyWay/laravel-mix/blob/v5.0.0/src/webpackPlugins/MockEntryPlugin.js) to remove the hashed mix file.

Addresses #9

### CODE REVIEW

**Comment by ctf0** [comment]
could u plz remove the semicolons

**Comment by Erutan409** [comment]
@ctf0 Done.

**Comment by ctf0** [comment]
awesome, thanx for ur hard work 🏅

**Comment by Erutan409** [comment]
@ctf0 So, this is fun.  I was doing a little more refactoring for the JSON manifest mutable stuff and realized what was part of the culprit from the beginning that negates the feature you just merged.

Using the `build` listener, [I was able to remove the aforementioned logic](https://github.com/Erutan409/laravel-mix-versionhash/commit/10f15fd323347347668be1c8b3637a4f2876f5b8) and simplify the overall functionality.

**Comment by ctf0** [comment]
awesome 
- is there any performance penalties with the new logic ? 
- and do we still have the flexibility to add any future capabilities with ease ?

**Comment by Erutan409** [comment]
I'd guess more than likely no performance hit. That build listener triggers when webpack is finished compiling. So, it should be non-blocking and shouldn't impose any overhead.

**Comment by ctf0** [comment]
perfect, last question, isnt `mix.webpackConfig().then` is the same as the event listener ?

**Comment by Erutan409** [comment]
The end result is the same, yes. But, the method chaining is a little redundant and, in my opinion, slightly misleading as to what's going on at first glance. Hooking onto webpackConfig() isn't doing anything in this context. Also, the way the manifest is being manipulated is [not synchronous](https://github.com/jprichardson/node-jsonfile/blob/master/README.md#readfilesyncfilename-options). Which, is probably why this was an issue with it not waiting until all the prerequisite logic was complete.

**Pull request merged**
